name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Validate block '
        id: validate-block
        uses: SummerOfBitcoin/code-challenge-2024-grader@v2
        with:
          test-name: 'Validate block '
          setup-command: chmod +x ./run.sh && ./run.sh
          command: chmod +x ./test.sh && ./test.sh
          timeout: 10
          max-fee: 20616923
          max-score: 100
      - name: Autograding Reporter
        uses: SummerOfBitcoin/autograding-grading-reporter@v2
        env:
          VALIDATE-BLOCK_RESULTS: "${{steps.validate-block.outputs.result}}"
        with:
          runners: validate-block
